const ROW_INDEX_TO_COUNT_AMOUNT_OF_RECORD = 2;
const COLUMN_INDEX_TO_COUNT_AMOUNT_OF_RECORD = 6;

const ROW_INDEX_TO_START_COLLECTING_RECORDS = 2;

const COLUMN_INDEX_OF_EXECUTING_DATE = 1;
const COLUMN_INDEX_OF_EXECUTING_TIME = 2;
const COLUMN_INDEX_OF_EXECUTING_SCRIPT_URL = 3;
const COLUMN_INDEX_OF_EXECUTING_METHOD_NAME = 4;

const COLUMN_LAST_INDEX_TO_COUNT_AMOUNT_OF_RECORD = 4;
